### ISSUE TITLE
Dist is broken

### ISSUE THREAD

**Issue by nlepage** [zenika-open-source/immutadot#330]
```
$ rollup -c config/rollup.js

/home/nico/git/znk/immutadot/packages/immutadot/src/index.js → dist/immutadot.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
packages/immutadot-parser/index.js
13:     global.index = mod.exports;
14:   }
15: })(this, function (exports, _consts, _toPath) {
       ^
16:   'use strict';
packages/immutadot-parser/consts.js
11:     global.consts = mod.exports;
12:   }
13: })(this, function (exports, _symbol) {
       ^
14:   'use strict';
[!] Error: 'toPath' is not exported by packages/immutadot-parser/index.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
packages/immutadot/src/core/apply.js (4:9)
2: import { nav } from 'nav/nav'
3: import { resolveGetter } from './get'
4: import { toPath } from '@immutadot/parser'
            ^
5: 
6: const getResolveArg = lazy => lazy ? resolveGetter : arg => arg
Error: 'toPath' is not exported by packages/immutadot-parser/index.js
    at error (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:13349:9)
    at handleMissingExport (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:13039:21)
    at Module.traceVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:13453:17)
    at ModuleScope.findVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:12726:29)
    at FunctionScope.Scope.findVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:4022:68)
    at BlockScope.Scope.findVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:4022:68)
    at BlockScope.Scope.findVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:4022:68)
    at FunctionScope.Scope.findVariable (/home/nico/git/znk/immutadot/node_modules/rollup/dist/rollup.js:4022:68)

error Command failed with exit code 1.
```

**Comment by nlepage** [comment]
Do we keep it ?

**Comment by nlepage** [comment]
I'm in favor of removing the dist, what do you think @frinyvonnick ?

**Comment by nlepage** [comment]
No more dist
